import os
import logging
import pandas as pd

logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR  = os.path.join(BASE_DIR, "data", "raw")

INPUT_FILES = {
    "facility":  "facility_outages.parquet",
    "generator": "generator_outages.parquet",
}


def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load raw parquet files generated by the connector"""
    facility_path  = os.path.join(DATA_DIR, INPUT_FILES["facility"])
    generator_path = os.path.join(DATA_DIR, INPUT_FILES["generator"])

    logger.info(f"Loading {facility_path}...")
    facility_df  = pd.read_parquet(facility_path)

    logger.info(f"Loading {generator_path}...")
    generator_df = pd.read_parquet(generator_path)

    logger.info(
        f"Loaded {len(facility_df)} facility records "
        f"and {len(generator_df)} generator records"
    )

    return facility_df, generator_df